[profile.default]
src = "src"
out = "out"
libs = ["lib", "node_modules"]
solc_version = "0.8.22"
optimizer = true
optimizer_runs = 200
via_ir = false

remappings = [
    "@layerzerolabs/lz-evm-oapp-v2/=node_modules/@layerzerolabs/lz-evm-oapp-v2/",
    "@layerzerolabs/lz-evm-protocol-v2/=node_modules/@layerzerolabs/lz-evm-protocol-v2/",
    "@layerzerolabs/lz-evm-messagelib-v2/=node_modules/@layerzerolabs/lz-evm-messagelib-v2/",
    "@openzeppelin/=node_modules/@openzeppelin/",
    "@pythnetwork/=node_modules/@pythnetwork/",
    "forge-std/=lib/forge-std/src/",
    "@evvm/=../Testnet-Contracts/src/"
]

[rpc_endpoints]
sepolia = "${RPC_URL_ETH_SEPOLIA}"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }
